apiVersion: batch/v1
kind: Job
metadata:
  name: multi-job
spec:
  completions: 5
  parallelism: 2
  template:
    spec:
      containers:
      - name: counter
        image: busybox
        command: ["sh", "-c", "echo Processing item && sleep 5"]
      restartPolicy: Never